default:
	javac -d . Utils.java
	javac -d . Token.java
	javac -d . SiteInterface.java
	javac -d . Site.java
	javac -d . SitesHandler.java
	javac -d . CriticalSection.java
	javac -d . RMIStuff.java
	javac -d . Process.java
clean:
	rm -f *.class
